server:
  port: 8080 #서버 포트지정
  error:
    include-message: always #Spring2.3부터 never가 default이므로 response에 담기지 않는 현상 해결

spring:
  profiles:
    default: test # 환경을 test로

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false #JSON 파싱 시 접근제한자 상관 없이 진행

  servlet:
    multipart:
      max-file-size: 1GB #최대 파일업로드 1GB 제한
      max-request-size: 1GB #파일업로드 요청 1GB 제한

  output:
    ansi:
      enabled: always #console color set

  main:
    allow-bean-definition-overriding: true #bean overriding true

app:
  name: changsol-server-template
  host: localhost:${server.port}

storage:
  location: ./files

#SrpingDoc 설정 API 문서화
springdoc:
  use-fqn: true #Scheme 중복 이슈 처리
  version: 1.0.0
  api-docs:
    path: /api-docs
  #Media Type 기본 값을 application/json
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  swagger-ui:
    #api 및 태그 정렬 기준을 알파벳 오름차순
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui
    #swagger-ui default url인 petstore html 문서 비활성화 여부
    disable-swagger-default-url: true
    display-request-duration: true  # try it out 을 했을 때 request duration 을 추가로 찍어줌
    #json화 된 config파일 대신 파라미터를 이용하여 swagger-ui에 접근
    #api-docs(/api-docs) 및 swagger-ui.configUrl(/api-docs/swagger-config)를 두번씩 호출하는 것을 방지
#    display-query-params-without-oauth2: true
  #OpenAPI 3 로 문서화할 api path 리스트
  paths-to-match:
    - /v1/**
    - /test/**

logging:
  level:
    org.changsol: debug
    org.hibernate.type.descriptor.sql: trace #SQL ?변수값
    org.hibernate.SQL: debug #SQL DML
  logback:
    #logFile
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
      file-name-pattern: ${app.host}.%d{yyyy-MM-dd}-%i.log
